version: '3.9'

services:
  database:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: universidades
